// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWGz7d1P_pO6mAI8jt4BiSwpdGxt3-UKU',
    appId: '1:862378525287:web:f0e562d82c02bf0164cac2',
    messagingSenderId: '862378525287',
    projectId: 'soundz-music-app-e3bc0',
    authDomain: 'soundz-music-app-e3bc0.firebaseapp.com',
    storageBucket: 'soundz-music-app-e3bc0.firebasestorage.app',
    measurementId: 'G-4Z6WBLLP6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrGBpZ_El2nUMiN28YyvZOZDsZloduPs',
    appId: '1:862378525287:android:7df254bbf689402964cac2',
    messagingSenderId: '862378525287',
    projectId: 'soundz-music-app-e3bc0',
    storageBucket: 'soundz-music-app-e3bc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vbwyoiLTZ6Gw0MYO8iXnhABSnhDnDis',
    appId: '1:862378525287:ios:4543872bb94a50b464cac2',
    messagingSenderId: '862378525287',
    projectId: 'soundz-music-app-e3bc0',
    storageBucket: 'soundz-music-app-e3bc0.firebasestorage.app',
    iosBundleId: 'com.example.soundzMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vbwyoiLTZ6Gw0MYO8iXnhABSnhDnDis',
    appId: '1:862378525287:ios:4543872bb94a50b464cac2',
    messagingSenderId: '862378525287',
    projectId: 'soundz-music-app-e3bc0',
    storageBucket: 'soundz-music-app-e3bc0.firebasestorage.app',
    iosBundleId: 'com.example.soundzMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWGz7d1P_pO6mAI8jt4BiSwpdGxt3-UKU',
    appId: '1:862378525287:web:f58ea3a79645e40f64cac2',
    messagingSenderId: '862378525287',
    projectId: 'soundz-music-app-e3bc0',
    authDomain: 'soundz-music-app-e3bc0.firebaseapp.com',
    storageBucket: 'soundz-music-app-e3bc0.firebasestorage.app',
    measurementId: 'G-5LDEHF70EQ',
  );
}
